version: "3.7"
services:
  api:
    container_name: getip-hit-counter
    build: .
    ports:
    - "80:80"
    links:
    - redis
  redis:
    container_name: redis-hit-counter
    image: redis:latest